### ISSUE TITLE
Extra Empty Line

### ISSUE THREAD

**Issue by svkpro** [d-bogankova/movies_lab#8]
It's not a good practice using extra empty lines:
`<?php
spl_autoload_register(function($class) {

    $path = __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . str_replace('\\', DIRECTORY_SEPARATOR, $class) . '.php';
    require_once($path);
}); `

**Comment by d-bogankova** [comment]
Extra line deleted
